import './style.css';
import './theme.css';
import {createIcons, AudioLines, Building2, LayoutDashboard, MessagesSquare, Lightbulb, Globe, ArrowUpRight, CircleHelp, Printer, CalendarDays, Search, Flag, Star, Smile, MessageSquare, ArrowRight, ShieldAlert} from 'lucide';
import {validateReport,summarize,filterRecords,frequency,selectInsights,SENTIMENTS,AREA_GROUPS,AREAS,ITEMS,SCALE} from './analysis.js';
const icons={AudioLines,Building2,LayoutDashboard,MessagesSquare,Lightbulb,Globe,ArrowUpRight,CircleHelp,Printer,CalendarDays,Search,Flag,Star,Smile,MessageSquare,ArrowRight,ShieldAlert};
const $=s=>document.querySelector(s);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const icon=name=>`<i data-lucide="${name}" aria-hidden="true"></i>`;
const state={page:'overview',from:'',through:'',sentiment:'all',area:'all',query:'',loading:true,error:false,limit:30};
let report={version:3,hotelName:'Reddington Chalets',publishedAt:null,executiveSummary:'',periods:[],records:[],insights:[]};
const rows=()=>filterRecords(report,state);
const period=id=>report.periods.find(p=>p.id===id);
const badge=s=>`<span class="badge ${s.toLowerCase()}">${esc(s)}</span>`;
const empty=(title,detail='Try changing the filters.')=>`<div class="empty"><h3>${title}</h3><p>${detail}</p></div>`;
function shell(){
 $('#app').innerHTML=`<a class="skip-link" href="#content">Skip to report</a><aside class="sidebar"><a class="brand" href="#overview">${icon('audio-lines')}<span>RedMonitor<span class="brand-dot">.</span></span></a><div class="hotel"><div class="hotel-icon">${icon('building-2')}</div><div><strong id="hotel-name"></strong><small>Guest experience report</small></div></div><div class="nav-label">YOUR REPORT</div><nav aria-label="Report sections">${[['overview','layout-dashboard','Overview'],['feedback','messages-square','Feedback'],['insights','lightbulb','Insights']].map(([id,ic,label])=>`<button data-page="${id}" aria-label="${label}">${icon(ic)}<span>${label}</span>${id==='feedback'?'<span class="nav-count"></span>':''}</button>`).join('')}</nav><div class="sidebar-bottom"><div class="hosting-card">${icon('globe')}<strong>A clearer view of every stay.</strong><p>Guest voices, carefully reviewed.</p><button data-page="about">About this report ${icon('arrow-up-right')}</button></div><div class="profile"><div class="avatar">R</div><div><strong>Reddington Chalets</strong><small>Anonymous findings</small></div></div></div></aside><div class="main-shell"><header class="topbar"><span>Report <span class="slash">/</span><strong id="breadcrumb"></strong></span><div class="top-actions"><span class="status-dot"></span><span>Scanned-form findings</span><button class="icon-button" data-page="about" aria-label="About this report">${icon('circle-help')}</button></div></header><main id="content" tabindex="-1"></main><footer>Made for better stays.<span>RedMonitor · Guest experience</span></footer></div>`;
 document.querySelectorAll('[data-page]').forEach(b=>b.onclick=()=>navigate(b.dataset.page));
 window.addEventListener('hashchange',()=>{const p=location.hash.slice(1);if(['overview','feedback','insights','about'].includes(p)){state.page=p;render();}});
 const initial=location.hash.slice(1);if(['overview','feedback','insights','about'].includes(initial))state.page=initial;
 render();
}
function navigate(page){state.page=page;location.hash=page;render();window.scrollTo(0,0);}
function heading(title,sub){return `<div class="page-heading"><div class="eyebrow">LISTEN. UNDERSTAND. IMPROVE.</div><div class="heading-line"><div><h1>${title}</h1><p>${sub}</p></div><button class="button secondary" id="print">${icon('printer')} Print report</button></div></div>`;}
function controls(){
 const options=(value)=>`<option value="">All periods</option>${report.periods.map(p=>`<option value="${p.start}" ${value===p.start?'selected':''}>${esc(p.label)}${p.status==='missing'?' · scans missing':''}</option>`).join('')}`;
 return `<section class="report-filters" aria-label="Report filters"><div class="period-controls"><label>From reporting period<select id="from">${options(state.from)}</select></label><label>Through reporting period<select id="through">${options(state.through)}</select></label><label>Sentiment<select id="sentiment"><option value="all">All sentiments</option>${SENTIMENTS.map(s=>`<option ${s===state.sentiment?'selected':''}>${s}</option>`).join('')}</select></label><label>Area mentioned<select id="area"><option value="all">All areas</option>${Object.entries(AREA_GROUPS).map(([group,areas])=>`<optgroup label="${esc(group)}">${areas.map(a=>`<option ${state.area===a?'selected':''}>${esc(a)}</option>`).join('')}</optgroup>`).join('')}</select></label><button class="text-button" id="reset">Reset filters</button></div><div class="filter-caption">Counts use supplied reporting periods. Findings follow the reporting-period range. Sentiment, area and search filters apply to charts and response lists.${state.query?` <span>Search: <strong>${esc(state.query)}</strong></span> <button class="text-button" id="clear-query">Clear search</button>`:''}</div></section>`;
}
function banner(){
 if(state.loading)return '<div class="notice" role="status">Loading the report…</div>';
 if(state.error)return '<div class="notice error-notice" role="alert">The report could not be loaded. Please reload the page.</div>';
 return `<div class="notice">${icon('globe')}<span><strong>Scanned forms only.</strong> Spreadsheet figures excluded. Guest identities removed. ${report.publishedAt?`Report prepared ${new Date(report.publishedAt).toLocaleDateString('en-GB',{day:'numeric',month:'short',year:'numeric',timeZone:'UTC'})}.`:''} <button class="inline-link" id="coverage-link">View source coverage</button></span></div>`;
}
function stats(data){const s=summarize(data);return `<div class="stats">${[
 ['messages-square','Distinct forms',s.count,'Forms in the selected view',''],
 ['star','Mean item score',s.average===null?'—':s.average.toFixed(2),`${s.answered.toLocaleString()} readable item scores · out of 4`,'gold'],
 ['smile','Positive feedback',s.count?`${Math.round(100*s.sentiments.Positive/s.count)}%`:'—',`${s.sentiments.Positive} positive · ${s.sentiments.Mixed} mixed`,'green'],
 ['flag','Forms raising concerns',s.concerns,`${s.sentiments.Negative} negative · concerns also occur in mixed forms`,'orange']
 ].map(([ic,label,value,note,color])=>`<section class="stat"><div class="stat-top">${label}<span class="stat-icon ${color}">${icon(ic)}</span></div><div class="stat-value">${value}</div><small>${note}</small></section>`).join('')}</div>`;}
function frequencyPanel(data){const series=frequency(report,data,state.from,state.through),max=Math.max(1,...series.map(p=>p.count||0));return `<section class="panel frequency-panel"><div class="panel-heading"><div><h2>Feedback frequency</h2><p>Distinct forms per supplied reporting period · click a period to focus</p></div>${icon('calendar-days')}</div><div class="frequency-bars">${series.map(p=>`<button class="frequency-row ${p.count===null?'missing-source':''}" data-period="${p.start}" aria-label="${esc(p.label)}: ${p.count===null?'scans missing':p.count+' forms'}"><span>${esc(p.label)}</span><span class="frequency-track">${p.count===null?'<span class="missing-label">Scans missing</span>':`<span style="width:${100*p.count/max}%"></span>`}</span><strong>${p.count===null?'—':p.count}</strong></button>`).join('')}</div><p class="method-note">Missing scans mean unknown feedback, not zero. Periods not supplied are omitted. These are form counts, not unique guests, occupancy or response rates. Some handwritten dates conflict with batch labels.</p></section>`;}
function sentimentPanel(data){const s=summarize(data);const colors={Positive:'#68c99e',Mixed:'#e1b562',Negative:'#ff526d',Neutral:'#87a9d1',Unclear:'#a192b6'};let cursor=0;const gradient=SENTIMENTS.map(k=>{const start=cursor;cursor+=s.count?s.sentiments[k]/s.count*100:0;return `${colors[k]} ${start}% ${cursor}%`;}).join(',');return `<section class="panel"><div class="panel-heading"><div><h2>How guests feel</h2><p>AI assessment of comments and selected answers</p></div></div><div class="sentiment-content"><div class="donut" role="img" aria-label="${SENTIMENTS.map(k=>`${s.sentiments[k]} ${k.toLowerCase()}`).join(', ')}" style="background:${s.count?`conic-gradient(${gradient})`:'#2b2c36'}"><div><strong>${s.count?Math.round(s.sentiments.Positive/s.count*100)+'%':'—'}</strong><span>positive</span></div></div><div class="sentiment-legend">${SENTIMENTS.map(k=>`<button data-sentiment="${k}" aria-label="Show ${k.toLowerCase()} feedback"><span class="dot" style="background:${colors[k]}"></span><span>${k}</span><strong>${s.sentiments[k]}</strong><small>${s.count?Math.round(s.sentiments[k]/s.count*100):0}%</small></button>`).join('')}</div></div><p class="method-note">Mixed retains praise or good ratings alongside concerns. Unclear is separate from neutral. Blank answers are never assumed positive or neutral.</p></section>`;}
function areasPanel(data,field='concerns'){const s=summarize(data);const areas=[...s.areas].filter(a=>a[field]).sort((a,b)=>b[field]-a[field]||a.name.localeCompare(b.name));const max=Math.max(1,...areas.map(a=>a[field]));return `<section class="panel area-panel"><div class="panel-heading"><div><h2>${field==='concerns'?'Where attention is needed':'What guests appreciate'}</h2><p>${field==='concerns'?'Written issues, requests or a “needs improvement” mark':'Explicit praise in comments'} · forms mentioning each area</p></div></div><div class="area-list">${areas.length?areas.map(a=>`<button class="area-row ${field}" data-area="${esc(a.name)}"><span>${esc(a.name)}${['Pest control','Room security'].includes(a.name)?'<small class="priority-marker">Priority check</small>':''}</span><span class="area-track"><span style="width:${a[field]/max*100}%"></span></span><strong>${a[field]}</strong></button>`).join(''):empty('No mentions in this view')}</div><p class="method-note">A form can mention several areas and can praise and criticize the same area. Counts overlap. Clicking an area includes both its concerns and praise.</p></section>`;}
function ratingsPanel(data){return `<section class="panel ratings-panel"><div class="panel-heading"><div><h2>The original item ratings</h2><p>1 Needs improvement · 2 Average · 3 Good · 4 Excellent</p></div></div><div class="table-scroll"><table class="item-table"><thead><tr><th>AREA / ITEM</th><th>MEAN / 4</th><th>ANSWERED</th><th>NEEDS IMPROVEMENT</th><th>UNCLEAR</th></tr></thead><tbody>${ITEMS.map(([group,label],i)=>{const values=data.map(r=>r.scores[i]).filter(v=>v!==null);return `<tr><td>${group} · ${label}</td><td>${values.length?(values.reduce((a,b)=>a+b,0)/values.length).toFixed(2):'—'}</td><td>${values.length}</td><td>${values.filter(v=>v===1).length}</td><td>${data.filter(r=>r.uncertainItems.includes(i)).length}</td></tr>`;}).join('')}</tbody></table></div><p class="method-note">The form has no overall score. The mean uses individual readable item marks on the original 1–4 scale. Blank, not-applicable and ambiguous marks are excluded; forms with more answered items contribute more marks. It is not a percentage satisfaction score.</p></section>`;}
function recordCard(r){return `<article class="response-card" id="${r.id}"><div class="response-top"><strong>${esc(r.id)}</strong><span>${esc(period(r.periodId)?.label)}</span>${badge(r.sentiment)}</div><p>${esc(r.summary)}</p><div class="response-tags">${r.concerns.map(a=>`<button class="topic-tag concern-tag" data-area="${esc(a)}">Concern · ${esc(a)}</button>`).join('')}${r.praises.map(a=>`<button class="topic-tag praise-tag" data-area="${esc(a)}">Praise · ${esc(a)}</button>`).join('')}</div><details class="score-detail"><summary>View item ratings${r.uncertainItems.length?` · ${r.uncertainItems.length} unclear`:''}</summary><dl>${ITEMS.map(([g,label],i)=>`<div><dt>${g} · ${label}</dt><dd>${r.scores[i]===null?r.uncertainItems.includes(i)?'Unclear':'Not answered / N/A':`${r.scores[i]} · ${SCALE[r.scores[i]-1]}`}</dd></div>`).join('')}</dl></details></article>`;}
function library(data,limit=state.limit){const sorted=[...data].sort((a,b)=>period(b.periodId).start.localeCompare(period(a.periodId).start)||a.id.localeCompare(b.id));return sorted.length?`<div class="response-list">${sorted.slice(0,limit).map(recordCard).join('')}</div>${sorted.length>limit?`<button class="button secondary" id="show-more">Show more · ${sorted.length-limit} remaining</button>`:''}`:empty('No feedback in this view');}
function findings(full=false){const scoped=selectInsights(report,state);const hasPeriod=Boolean(state.from||state.through);return `<section class="panel insight-panel"><div class="panel-heading"><div><h2>Findings & recommended actions</h2><p>${hasPeriod?'Prepared findings for the selected reporting periods':'Prepared analysis of the complete report'}</p></div></div>${scoped.slice(0,full?10000:4).map(i=>`<article class="insight ${i.type==='strength'?'positive-insight':''} ${i.priority==='high'?'high-priority':''}"><div class="insight-label">${icon(i.priority==='high'?'shield-alert':'flag')}${i.priority==='high'?'PRIORITY CHECK':i.type.toUpperCase()}</div><h3>${esc(i.title)}</h3>${i.periodId?`<p class="insight-period"><strong>${esc(period(i.periodId)?.label)}</strong></p>`:''}<p>${esc(i.detail)}</p><p><strong>Recommended action:</strong> ${esc(i.recommendation)}</p><details class="evidence"><summary>${i.responseIds.length} supporting forms</summary><ul>${i.responseIds.map(id=>{const r=report.records.find(r=>r.id===id);return `<li><strong>${id}</strong> · ${esc(period(r.periodId).label)} ${badge(r.sentiment)}<p>${esc(r.summary)}</p></li>`;}).join('')}</ul></details></article>`).join('')}${!scoped.length?empty('No prepared findings for this period','No supported recommendations are available for the selected range. Missing scans remain unknown.'):''}${!full&&scoped.length>4?'<button class="text-button" id="all-findings">View all findings →</button>':''}<p class="method-note">Recommendations are proposed actions, not completed work. Guest reports have not been independently verified. Priority reflects potential impact, not just frequency.</p></section>`;}
function executive(){return !state.from&&!state.through&&report.executiveSummary?`<section class="panel executive-summary"><div class="eyebrow">THE BIGGER PICTURE · COMPLETE REPORT</div><h2>What the feedback tells us</h2><p>${esc(report.executiveSummary)}</p></section>`:'';}
function coverage(){return `<section class="panel coverage-panel" id="coverage"><div class="panel-heading"><div><h2>Source coverage & limitations</h2><p>Complete supplied inventory · independent of filters</p></div></div><div class="coverage-totals"><span><strong>${report.periods.reduce((n,p)=>n+p.scannedPages,0)}</strong> PDF pages reviewed</span><span><strong>${report.periods.reduce((n,p)=>n+p.duplicateForms,0)}</strong> repeated forms excluded</span><span><strong>${report.periods.filter(p=>p.status==='missing').length}</strong> batch without scans</span></div><div class="table-scroll"><table><thead><tr><th>SUPPLIED PERIOD</th><th>PDF PAGES</th><th>FORMS COUNTED</th><th>REPEATS EXCLUDED</th><th>EVIDENCE NOTES</th></tr></thead><tbody>${report.periods.map(p=>`<tr><td class="nowrap">${esc(p.label)}</td><td>${p.scannedPages}</td><td>${p.status==='missing'?'Unknown — scans missing':p.observedForms-p.duplicateForms}</td><td>${p.duplicateForms}</td><td class="coverage-note">${esc(p.note)}</td></tr>`).join('')}</tbody></table></div><p class="method-note">Spreadsheets were used only as reference for supplied reporting-period labels; no spreadsheet ratings, totals or comments were imported. This reconstruction does not establish whether another report was intentionally misrepresented. Date labels are not verified individual response dates. Distinct forms may come from the same guest; only confirmed repeated scans were removed.</p></section>`;}
function about(){return heading('About this report','How the scans become anonymous, reviewable findings.')+banner()+`<section class="panel methodology"><h2>From forms to findings</h2><p>AI visually reads the source forms outside this website, records selected answers, paraphrases comments and prepares the findings. The website only displays that prepared data and calculates totals. Names, contact details, signatures, room numbers and raw forms are excluded.</p><h2>Sentiment</h2><p><strong>Positive:</strong> favourable comments and/or predominantly good or excellent marks with no clear complaint. <strong>Mixed:</strong> favourable evidence alongside a complaint, specific request or needs-improvement mark. <strong>Negative:</strong> a predominantly adverse assessment. <strong>Neutral:</strong> readable feedback without a favourable or adverse assessment. <strong>Unclear:</strong> insufficient readable evidence to classify confidently. Zero neutral forms is a valid result.</p><h2>Areas and emphasis</h2><p>Concern tags identify written issues, improvement requests or explicit score-1 selections. Praise tags identify explicit favourable comments. An average (2) item mark alone does not automatically create a concern tag. The original item table retains those average ratings. Safety and hygiene findings receive priority based on potential impact, with evidence counts shown.</p><h2>Frequency and ratings</h2><p>Frequency counts distinct forms within supplied reporting batches, including forms with no readable rating. Missing source batches show unknown, never zero. The from/through selectors include whole reporting periods; no daily or calendar-month counts are inferred. Some handwritten dates disagree with batch labels. No occupancy or invitation counts were supplied, so response rates cannot be calculated.</p><p>The original scale is 1 Needs improvement, 2 Average, 3 Good and 4 Excellent. There is no overall rating field. Item means use only clear answers; blank, not-applicable and ambiguous answers are excluded. The number of readable marks is shown with each mean. Overwritten or conflicting marks remain unclear.</p><h2>Limits of the evidence</h2><p>AI can misread faint handwriting or marks. Uncertainty is retained for review. This report reflects only the supplied scans; it does not verify the truth of individual complaints or establish the completeness of the hotel's feedback collection. Findings and recommendations are prepared separately for each reporting period. Selecting a range shows those period-specific findings and their evidence. With all periods selected, the complete-report synthesis is shown. Sentiment, area and search filters affect charts and response lists, not the period findings.</p><h2>Public anonymous summaries</h2><p>Anyone who can access this website can read and download its published data. Scans and private extraction records remain outside the website.</p></section>`+coverage();}
function render(){
 const titles={overview:'Overview',feedback:'Feedback',insights:'Insights',about:'About this report'};
 $('#hotel-name').textContent=report.hotelName;$('#breadcrumb').textContent=titles[state.page];$('.nav-count').textContent=report.records.length;
 document.querySelectorAll('nav [data-page]').forEach(b=>{b.classList.toggle('active',b.dataset.page===state.page);b.setAttribute('aria-current',b.dataset.page===state.page?'page':'false');});
 const data=rows();
 let html='';
 if(state.page==='about')html=about();
 else if(state.page==='feedback')html=heading('The feedback library','Anonymous summaries, specific areas and the original item ratings.')+controls()+banner()+`<section class="panel"><div class="filter-row"><label class="search">${icon('search')}<input id="search" type="search" aria-label="Search feedback" placeholder="Search summaries, areas or response IDs" value="${esc(state.query)}"></label><span id="result-count" class="muted" aria-live="polite">${data.length} forms</span></div><div id="library">${library(data)}</div></section>`;
 else if(state.page==='insights')html=heading('Turn listening into action.','Evidence, priorities and practical improvements.')+controls()+banner()+`<div class="scope-note">Findings below follow the selected reporting-period range. Each finding cites evidence from its period. Area counts also follow sentiment, area and search filters.</div><div class="detail-grid">${findings(true)}<div class="panel-stack">${areasPanel(data)}${areasPanel(data,'praises')}</div></div>`;
 else html=heading('Every stay tells a story.','A clear view of guest sentiment, recurring concerns and feedback over time.')+controls()+banner()+executive()+stats(data)+`<div class="chart-grid">${frequencyPanel(data)}${sentimentPanel(data)}</div><div class="detail-grid">${areasPanel(data)}${areasPanel(data,'praises')}</div><div class="detail-grid">${findings()}${ratingsPanel(data)}</div><section class="panel recent-panel"><div class="panel-heading"><div><h2>Recent feedback</h2><p>Latest supplied reporting periods</p></div><button class="text-button" id="view-all">View all feedback ${icon('arrow-right')}</button></div>${library(data,5)}</section>`+coverage();
 $('#content').innerHTML=html;
 bind();createIcons({icons,attrs:{'stroke-width':1.7}});
}
function bind(){
 for(const key of ['from','through','sentiment','area'])if($('#'+key))$('#'+key).onchange=e=>{state[key]=e.target.value;state.limit=30;if(state.from&&state.through&&state.from>state.through){if(key==='from')state.through=state.from;else state.from=state.through;}render();};
 if($('#reset'))$('#reset').onclick=()=>{Object.assign(state,{from:'',through:'',sentiment:'all',area:'all',query:'',limit:30});render();};
 if($('#clear-query'))$('#clear-query').onclick=()=>{state.query='';render();};
 if($('#print'))$('#print').onclick=()=>window.print();
 if($('#coverage-link'))$('#coverage-link').onclick=()=>{if(state.page!=='overview'&&state.page!=='about')navigate('about');$('#coverage')?.scrollIntoView({behavior:'smooth'});};
 if($('#view-all'))$('#view-all').onclick=()=>navigate('feedback');
 if($('#all-findings'))$('#all-findings').onclick=()=>navigate('insights');
 if($('#show-more'))$('#show-more').onclick=()=>{if(state.page!=='feedback'){navigate('feedback');return;}state.limit+=30;$('#library').innerHTML=library(rows());bind();};
 document.querySelectorAll('[data-period]').forEach(b=>b.onclick=()=>{state.from=state.through=b.dataset.period;render();});
 document.querySelectorAll('[data-sentiment]').forEach(b=>b.onclick=()=>{state.sentiment=b.dataset.sentiment;render();});
 document.querySelectorAll('[data-area]').forEach(b=>b.onclick=()=>{state.area=b.dataset.area;state.query='';state.limit=30;navigate('feedback');});
 if($('#search'))$('#search').oninput=e=>{state.query=e.target.value;state.limit=30;const filtered=rows();$('#library').innerHTML=library(filtered);$('#result-count').textContent=`${filtered.length} forms`;bind();};
}
shell();
try{const response=await fetch(`${import.meta.env.BASE_URL}data/dashboard.json`,{cache:'no-store'});if(!response.ok)throw new Error('Unavailable');report=validateReport(await response.json());}catch{state.error=true;}finally{state.loading=false;render();}
